# Generated by Django 5.2.13 on 2026-04-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Verification Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
